<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>

    <AssemblyName>GiHATE</AssemblyName>
    <RootNamespace>GiHATE</RootNamespace>
    <Title>GiHATE</Title>
    <Product>GiHATE</Product>
    <Company>Gabrielzv1233</Company>
    <Authors>Gabrielzv1233</Authors>
    <Description>GIGABYTE GiMATE hardware button disabler and programmable key remapper.</Description>
    <Copyright>Copyright © Gabrielzv1233 2026</Copyright>
    <NeutralLanguage>en-US</NeutralLanguage>

    <Version>0.2.0</Version>
    <AssemblyVersion>0.2.0.0</AssemblyVersion>
    <FileVersion>0.2.0.0</FileVersion>
    <InformationalVersion>0.2.0</InformationalVersion>

    <RepositoryUrl>https://github.com/gabrielzv1233/GiHATE</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://github.com/gabrielzv1233/GiHATE</PackageProjectUrl>

    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>false</EnableCompressionInSingleFile>

    <Deterministic>true</Deterministic>
    <DebugType>embedded</DebugType>
  </PropertyGroup>
</Project>
